### ISSUE TITLE
How to generate 33, 61, 77 files

### ISSUE THREAD

**Issue by youcaizhu** [jxzhangcc/PIO-py3#1]
%chk=CH4.chk
%mem=20GB
%nprocshared=12
#p opt freq b3lyp def2svp emp=gd3 scf=xqc pop=nboread

CH4

0 1
 C                  0.24027460    2.82036609    0.00000000
 H                  0.59692903    1.81155609    0.00000000
 H                  0.59694744    3.32476428    0.87365150
 H                  0.59694744    3.32476428   -0.87365150
 H                 -0.82972540    2.82037927    0.00000000

$nbo FILENAME=CH4 AONAO=W33 FNAO=W61 DMNAO=W71 $end

hello，this is my input file. I use the g09 in the linux, but i can't find a 33,61,and 77 files. How do I generate the appropriate file? thanks！

**Comment by jxzhangcc** [comment]
Sorry I just see your issue. I'm not very active on GitHub. Has your issue been resolved? Your input file seems perfectly fine and works on my computer. If your issue is persistent, send an email to zhangjxcc@163.com
